# Site settings
title: Thomas Mosher
email: tmosh5@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thomasmosher.github.io" # the base hostname & protocol for your site

github_username: tmosh5

linkedin_username: thomas-mosher

# Build settings
markdown: kramdown
